version: '3'

services:
  app:
    build: ./app
    ports:
     - "8000:8000"
    image: "ck401-dev-app"
    environment:
     - L_USERNAME=${L_USERNAME}
     - L_PASSWORD=${L_PASSWORD}
     - L_DB=${L_DB}

  scraper:
    build: ./scraper
    image: "ck401-dev-scraper"
    environment:
     - L_USERNAME=${L_USERNAME}
     - L_PASSWORD=${L_PASSWORD}
     - L_DB=${L_DB}
     - L_DROPBOX=${L_DROPBOX}
