version: '3'

services:
  app:
    build: ./app
    ports:
     - "8000:8000"
    image: "fallenverse/lecture-scraper_web:latest"
    environment:
     - L_USERNAME=${L_USERNAME}
     - L_PASSWORD=${L_PASSWORD}
     - L_DB=${L_DB}

  scraper:
    build: ./scraper
    image: "fallenverse/lecture-scraper_back:latest"
    environment:
     - L_USERNAME=${L_USERNAME}
     - L_PASSWORD=${L_PASSWORD}
     - L_DB=${L_DB}
     - L_DROPBOX=${L_DROPBOX}
